all: test build dist

.PHONY: build
build: proto_ts_definitions
	npm run build

dist: proto_ts_definitions
	npm run dist

# Generate typescript definitions for our protobuf messages
.PHONY: proto_ts_definitions
proto_ts_definitions: node_modules
	./node_modules/protobufjs/bin/pbjs -t static-module -w commonjs -o modules/proto/index.js \
	proto/{client,markets,stream}/*.proto
	./node_modules/protobufjs/bin/pbjs \
		-t static-module proto/{client,markets,stream}/*.proto \
		| ./node_modules/protobufjs/bin/pbts -o proto.d.ts -
	# disbale tslint in here because pbts tool complains; it works fine though
	echo "/* tslint:disable */" > modules/proto/index.d.ts
	echo "\n/* GENERATED BY MAKEFILE */\n" >> modules/proto/index.d.ts
	cat proto.d.ts >> modules/proto/index.d.ts
	rm proto.d.ts

node_modules:
	yarn

.PHONY: test
test: node_modules
	timeout -k 5s 150s npm test

.PHONY: clean
clean:
	rm -rf build dist

difftest: dist
	@TMP=$$(mktemp -t checkout-diff.XXXXXX) ; \
    git diff dist/ > $$TMP ; \
    if [ -s "$$TMP" ]; then \
      echo Found diffs in checkout:; git status -s; head -n 50 "$$TMP"; \
      rm $$TMP; \
      exit 1; \
    fi; \
    rm $$TMP;
